version: '3'
services:
  pgsql-zabbix:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zabbix, alerta
      POSTGRES_PASSWORD: zabbix, alerta
      POSTGRES_DATABASE: zabbix, alerta
    volumes:
      - ./pgsql:/var/lib/pgsql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.4-alpine-latest
    ports:
      - "10050-10051:10050-10051"
    environment:
      DB_SERVER_HOST: pgsql-zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DATABASE: zabbix
    depends_on:
      - pgsql-zabbix
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.4-alpine-latest
    ports:
      - "80:8080"
    environment:
      DB_SERVER_HOST: pgsql-zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DATABASE: zabbix
      ZBX_SERVER_NAME: sb-virtualbox
    depends_on:
      - pgsql-zabbix
    networks:
      - zabbix-network
  
  zabbix-agent2:
    image: zabbix/zabbix-agent2:6.4-alpine-latest
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    env_file:
      - ./.env_agent2
    privileged: true
    pid: "host"
    networks:
      - zabbix-network
    stop_grace_period: 30s
  
  alerta:
    image: alerta/alerta-web:latest
    # volumes:
      # - $PWD/config/config.json:/web/config.json
    ports:
      - 80:8081
    depends_on:
      - pgsql-zabbix
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/alerta
      - AUTH_REQUIRED=True
      - ADMIN_PASSWORD=alerta # default is "alerta"
      - ADMIN_USERS=admin@alerta.io
      - PLUGINS=reject,blackout,zabbix
      - INSTALL_PLUGINS=zabbix
      - ZABBIX_API_URL=http://zabbix-web
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
